'use strict';
// Behavior checks in a minimal DOM harness, not a browser rendering test.
// The shared Python fixture builder parses the generated, self-contained page.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..');
const fixture=JSON.parse(fs.readFileSync(path.join(root,'.checks/ballot_dom_fixture.json')));
const DATA=JSON.parse(fs.readFileSync(path.join(root,'2026-11-03_Bay_Area_Elections.json')));
let downloads=[],blobs=new Map();
class Element{constructor(tag,attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.children=[];this.events={};this.dataset={};this.hidden='hidden'in attrs;this.open='open'in attrs;this._value=attrs.value;}append(...xs){for(const x of xs){this.children.push(x);if(typeof x==='object')x.parent=this;}}replaceChildren(...xs){this.children=[];this.append(...xs);}get textContent(){return this.children.map(x=>typeof x==='string'?x:x.textContent).join('');}set textContent(x){this.children=[String(x)];}get value(){return this._value??this.options[0]?.value??'';}set value(x){this._value=String(x);}get options(){return this.children.filter(x=>typeof x==='object'&&x.tagName==='OPTION');}setAttribute(k,v){this.attrs[k]=String(v);}removeAttribute(k){delete this.attrs[k];}addEventListener(k,f){(this.events[k]??=[]).push(f);}async fire(k){await Promise.all((this.events[k]||[]).map(f=>f({preventDefault(){},target:this})));}click(){if(this.download)downloads.push(blobs.get(this.href));return this.fire('click');}remove(){this.parent.children=this.parent.children.filter(x=>x!==this);}focus(){}scrollIntoView(){}}
const inflate=x=>{if(typeof x==='string')return x;const e=new Element(x.tag,x.attrs);e.append(...x.children.map(inflate));return e;};const dom=inflate(fixture);const nodes=(n=dom)=>[n,...n.children.filter(x=>typeof x==='object').flatMap(nodes)];const $=id=>nodes().find(x=>x.attrs.id===id);assert.deepEqual(JSON.parse($('election-data').textContent),DATA,'Built page must embed current dataset');assert.equal($('voting-address').attrs.name,undefined,'No native GET form parameter may contain the address');const document={createElement:t=>new Element(t),getElementById:$,body:nodes().find(x=>x.tagName==='BODY'),addEventListener(){},removeEventListener(){}};for(const element of nodes()){element.ownerDocument=document;} $('voting-address').form=$('address-form');const testURL=URL;testURL.createObjectURL=b=>{const u='blob:test-'+blobs.size;blobs.set(u,b);return u;};testURL.revokeObjectURL=()=>{};
let response,lookupCount=0;const service={lookup:async(address,opts)=>{lookupCount++;assert(opts.signal instanceof AbortSignal);if(response instanceof Error)throw response;return response;}};
const ctx={document,location:{href:'https://salqadri.github.io/bay-area-elections-2026/ballot.html'},URL:testURL,URLSearchParams,Intl,Date,AbortController,Blob,console,setTimeout:()=>1,clearTimeout(){},ElectionAddressService:service};vm.createContext(ctx);const scripts=nodes().filter(n=>n.tagName==='SCRIPT'&&!n.attrs.type);assert.equal(scripts.length,5);for(let i=1;i<scripts.length;i++)vm.runInContext(scripts[i].textContent,ctx,{filename:'embedded-ballot-module-'+i+'.js'});assert.equal($('voting-address').attrs.role,'combobox');assert.equal($('voting-address').attrs['aria-expanded'],'false');assert($('address-suggestions').hidden);const cards=()=>nodes().filter(x=>x.dataset.contestId);const groups=()=>nodes().filter(x=>x.dataset.level);const text=id=>$(id).textContent;
const census=(county,city)=>({matchedAddress:county==='Santa Clara'?'200 E SANTA CLARA ST, SAN JOSE, CA, 95113':'1 DR CARLTON B GOODLETT PL, SAN FRANCISCO, CA, 94102',coordinates:{x:-121,y:37},geographies:{States:[{STATE:'06'}],Counties:[{STATE:'06',NAME:county+' County'}],'Incorporated Places':[{STATE:'06',NAME:city+' city'}],'119th Congressional Districts':[{STATE:'06',CD119:'17'}],'2026 State Legislative Districts - Lower':[{STATE:'06',SLDL:county==='Santa Clara'?'025':'017'}],'2026 State Legislative Districts - Upper':[{STATE:'06',SLDU:county==='Santa Clara'?'015':'011'}]}});
(async()=>{assert.equal($('manual-county').options.length,6);$('manual-county').value='Santa Clara';await $('browse-county').click();assert(!$('ballot-results').hidden);assert(cards().length>80);assert(text('ballot-warning-list').includes('Not all possible races'));assert(groups().some(g=>!g.open));await $('ballot-collapse-all').click();assert(groups().every(g=>!g.open));await $('ballot-expand-all').click();assert(groups().every(g=>g.open));const evDetails=nodes().filter(x=>x.tagName==='DETAILS'&&(x.className===undefined?String(x.attrs.class||''):x.className)==='ballot-candidate-evidence');assert(evDetails.length>0&&evDetails.every(d=>d.parent?.tagName==='LI'),'Gaza evidence details must nest inside the candidate li, never directly in ul');assert(cards().every(c=>c.textContent.includes('details')));const stateRaces=cards().filter(c=>DATA.positions.find(p=>p.id===c.dataset.contestId).government_level==='State');assert.equal(DATA.positions.find(p=>p.id===stateRaces[0].dataset.contestId).office_category,'State Senate');assert(cards().filter(c=>DATA.positions.find(p=>p.id===c.dataset.contestId).election_type==='retention').every(c=>c.textContent.includes('Yes / No retention vote')));
assert(text('ballot-results').includes('Endorsed by CAIR Action'));assert(text('ballot-results').includes('Preferred by CAIR Action'));const marcCard=cards().find(c=>c.dataset.contestId==='CA2026-150');assert(marcCard.textContent.includes('Opposed by CAIR Action'));assert(marcCard.textContent.includes('1 opposed'));assert(!marcCard.textContent.includes('Endorsed by CAIR Action'));
assert(text('ballot-results').includes('supplied capture of CAIR Action'));
assert(text('ballot-results').includes('Source rating: Strong Support'));
assert(!text('ballot-results').includes('Endorsed by California Jewish Democrats'));
const endorsementDetails=nodes().filter(x=>x.tagName==='DETAILS'&&x.className==='ballot-candidate-endorsements');
assert(endorsementDetails.length>0&&endorsementDetails.every(d=>d.parent?.tagName==='LI'));
$('voting-address').value='test address';response={matches:[census('Santa Clara','San Jose')],provider:'US Census',queriedAt:'2026-10-06'};await $('address-form').fire('submit');assert.equal(lookupCount,1);assert($('address-matches').hidden);assert(text('ballot-context-values').includes('200 E SANTA CLARA ST'));assert(cards().some(c=>c.dataset.confidence==='district_uncertain'));assert(cards().every(c=>DATA.positions.find(p=>p.id===c.dataset.contestId).counties.includes('Santa Clara')));assert(!$('find-ballot').disabled);
response={matches:[census('Santa Clara','San Jose'),census('San Francisco','San Francisco')],provider:'US Census',queriedAt:'2026-10-06'};await $('address-form').fire('submit');assert(!$('address-matches').hidden);assert.equal($('address-match').value,'all');assert.equal($('address-match').options.length,3);assert(text('ballot-warning-list').includes('Multiple addresses matched'));assert(text('ballot-results').includes('archive bound; original date unknown'),'Ballot evidence must label archive bounds');const unionCount=cards().length;$('address-match').value='1';await $('address-match').fire('change');assert(cards().length<unionCount);assert(cards().every(c=>DATA.positions.find(p=>p.id===c.dataset.contestId).counties.includes('San Francisco')));await $('download-estimate').click();const exportText=await downloads.at(-1).text();const exported=JSON.parse(exportText);assert(!exportText.includes('CARLTON'));assert(!exportText.includes('matchedAddresses'));assert(!exportText.includes('"coordinates":'));assert(exported.races.length===cards().length);
response={matches:[]};await $('address-form').fire('submit');assert($('ballot-results').hidden);assert(text('lookup-error').includes('No matching address'));response=Error('offline');await $('address-form').fire('submit');assert(text('lookup-error').includes('temporarily unavailable'));assert(!$('find-ballot').disabled);
response={matches:[{matchedAddress:'1 MAIN ST, RENO, NV',geographies:{States:[{STATE:'32'}],Counties:[{STATE:'32',NAME:'Washoe County'}]}}]};await $('address-form').fire('submit');assert(!$('ballot-empty').hidden);assert(text('ballot-empty-title').includes('outside'));assert.equal(cards().length,0);assert($('ballot-stats').hidden);
let resolveLate;service.lookup=()=>new Promise(resolve=>{resolveLate=resolve;});const pending=$('address-form').fire('submit');assert($('find-ballot').disabled);$('manual-county').value='Alameda';await $('browse-county').click();resolveLate({matches:[census('San Francisco','San Francisco')]});await pending;assert(text('ballot-results-title').includes('county'));assert(text('ballot-context-values').includes('Alameda'));assert(cards().every(c=>DATA.positions.find(p=>p.id===c.dataset.contestId).counties.includes('Alameda')));assert(!$('find-ballot').disabled);
assert(text('ballot-results').includes('Supported by Dr. Romesh Japra'));
assert(text('ballot-results').includes('Endorsed by Americans4Hindus'));
assert(!text('ballot-results').includes('Endorsed by Dr. Romesh Japra'));
const report={passed:true,environment:'Minimal DOM integration harness; not a browser rendering test',checks:['Endorsements distinguish support, source ratings, campaign claims and secondary reports; notes remain visible inside candidate list items','Current embedded dataset and five county selector choices','County fallback and Senate-first office priority','Judicial retention uses Yes / No metadata','Expand and collapse all sections','Gaza evidence <details> nests inside its candidate <li>, preserving list semantics','Archive bounds are visibly distinct from publication dates','Single-address match renders real matcher results','Multiple address matches union by default, with explicit narrowing','Downloaded estimate omits raw matched addresses and coordinates','No-match, network-failure and outside-scope messages','Stale lookup response cannot replace a newer manual county estimate','Address cannot become a native GET form parameter']};report.check_count=report.checks.length;fs.mkdirSync(path.join(root,'.checks'),{recursive:true});fs.writeFileSync(path.join(root,'.checks/ballot_page_test_report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
